### ISSUE TITLE
Q: How does this relate to camfindlay/twofactorauth?

### ISSUE THREAD

**Issue by micschk** [dhensby/silverstripe-mfa#4]
Is the purpouse of this module to add external authentication as well (e.g. Facebook/Google)?

**Comment by dhensby** [comment]
> Q: How does this relate to camfindlay/twofactorauth
There is no formal relation - though they'd both do "the same thing" for an end user point of view.

>Is the purpouse of this module to add external authentication as well (e.g. Facebook/Google)?
no

This module is still very much under development
